# Name to identify the Python type of the environment from the ENV_TYPES registry
type: door

# Action frequency in Hz. Only divisors of 240 are supported.
action_frequency: 30

# Angle at which the door is considered open.
open_threshold: 35 # Degrees

# Configuration of the door
door:
  # Path to the URDF file of the door
  path: package://rl_tasks/objects/door.urdf
  # Name of the root link
  reference_link: base_link
  # Bounds of the position sampling of the door.
  # XYZ world coordinates in meters.
  sampler:
    min: [0.7, -0.05, 0]
    max: [0.75, 0.05, 0]

# Observational noise
noise:
  # Noise of "position" observation
  position:
    variance: 0.0
    constant: true # Constant over one episode
  gripper_width:
    variance: 0.0
    constant: true # Constant over one episode
  # Force experienced at robot wrist
  force:
    variance: 0.0
    constant: true # Constant over one episode
  # Torque experienced at robot wrist
  torque:
    variance: 0.0
    constant: true # Constant over one episode
  # Joint positions of the door
  doorpos:
    variance: 0.0
    constant: true # Constant over one episode
  # Joint positions of the door handle
  handlepos:
    variance: 0.0
    constant: true # Constant over one episode

# Robot configuration
robot:
  # Path to the URDF file of the robot
  path: package://rl_tasks/robots/panda_hand.urdf
  # Name of end-effector link
  eef: panda_hand_tcp
  # Name of the joint measuring external wrench
  ft_joint: panda_hand_joint
  # Name of finger joints
  fingers: 
    - panda_finger_joint1
    - panda_finger_joint2
  # Configuration of initial pose sampler
  initial_pose:
    # Starting pose for IK-solver
    q: [0, -0.2, 0.0, -2.5, 1.6, 2.6, 0.7853981633974483]
    # Starting pose of robot end-effector
    position: [0.45, 0, 0.35]
    orientation: [-2.2, 0, -1.57]
    # Starting gripper width
    gripper_width: 0.1
  # Controller used to interpret actions
  controller: virtual   # Options: relative, virtual
