# Name to identify the Python type of the environment from the ENV_TYPES registry
type: peg

# Action frequency in Hz. Only divisors of 240 are supported.
action_frequency: 30

# Configuration of the board in which the robot should insert the peg
board:
  # Path to the URDF file of the board
  path: package://bopt_gmm/objects/board_easy.urdf
  # Bounds of the position sampling of the board.
  # XYZ world coordinates in meters.
  sampler:
    min: [0.5, -0.1, 0]
    max: [0.55, 0.1, 0]

# Configuration of the peg to be inserted
peg:
  # Path to the URDF file of the peg
  path: package://bopt_gmm/objects/cylinder.urdf

# Observational noise
noise:
  # Noise of "position" observation
  position:
    variance: 0.0
    constant: true
  gripper_width:
    variance: 0.0
    constant: true # Constant over one episode
  # Force experienced at robot wrist
  force:
    variance: 0.0
    constant: true # Constant over one episode
  # Torque experienced at robot wrist
  torque:
    variance: 0.0
    constant: true # Constant over one episode

# Robot configuration
robot:
  # Path to the URDF file of the robot
  path: package://bopt_gmm/robots/panda_hand.urdf
  # Name of end-effector link
  eef: panda_hand_tcp
  # Name of the joint measuring external wrench
  ft_joint: panda_hand_joint
  # Name of finger joints
  fingers:
    - panda_finger_joint1
    - panda_finger_joint2
  # Configuration of initial pose sampler
  initial_pose:
    # Starting pose for IK-solver
    q: [0, -0.3, 0, -2.2, 0, 2.0, 0.7853981633974483]
    # Starting pose of robot end-effector
    position: [0.35, 0, 0.30]
    orientation: [1, 0, 0, 0]
    # Starting gripper width
    gripper_width: 0.05
